### ISSUE TITLE
 Invalid Null Value.mp4

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#151] opened 2020-08-25 20:27 UTC
Screengrab/videos (insert file names here)
2020 08 25, Invalid Null Value.mp4

Link
registry.boston.gov/death

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOs 10.15.5 > Chrome 84

Trusted Tester Test
N/a

Brief Description
Functional bug – when testing for accessibility, came across a null value on a death certificate information. 

Steps to reproduce
1)	00:00, Go to site, using the link provided above.
2)	00:02, Used a common name to test website, in this case, “Patrick Ryan”
3)	00:04, All “Patrick Ryan” names appear in search
4)	00:15, Note that Patrick Ryan (highlighted in red) has a null value for age. This is a content bug as “null” should not be shown. As a suggestion, “unknown” would be used when the age is unavailable.

Desired Result
•	Able to view death certificate information without content error (null.)

Actual Result
•	Unable to view death certificate information without content error (null)

**Comment by reillyzlab** [comment] 2020-10-08 17:54
@jill-iterators there is a video link suggested but no file we can access. Can you add the video file so we can fully understand the issue?

**Comment by reillyzlab** [comment] 2020-10-09 14:21
closing duplicate of #178

**Closed as completed by reillyzlab** 2020-10-09 14:21 UTC
Labels: Functional, Certificate
