### ISSUE TITLE
Clicking Search on My Neighborhood page causes search feature to disappear

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#208] opened 2020-12-18 18:27 UTC
Screengrab/videos (insert file names here)
2020 12 18, Clicking Search on My Neighborhood page causes search feature to disappear.mp4
[2020 12 18, Clicking Search on My Neighborhood page causes search feature to disappear.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5717450/2020.12.18.Clicking.Search.on.My.Neighborhood.page.causes.search.feature.to.disappear.mp4.zip)

Link
https://www.boston.gov/my-neighborhood

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 11.1 > Chrome 87

Brief Description
Clicking Search on My Neighborhood page causes search feature to disappear

Steps to reproduce
1)	00:00, Open the link in a private browser window, click on the search text field with the text “Enter your address” in it
2)	00:01, Enter in the address that you are searching for
3)	00:07, Click on an address from the list below the search text field
a)	Bug: For a second, text saying “Loading …” shows up and then the text and the search text field and search button disappears

Desired Result
•	The search results that were being looked for show up

Actual Result
•	The search text field, search button disappears, and no results show up from the search.

**Comment by subaha-cob** [comment] 2020-12-19 16:29
@jill-iterators This is not a failure because you were on UAT. There are no content in UAT for all the addresses except for the five I mentioned below:

50 Milk St #2050 Boston, 02108
192 Dudley St Roxbury, 02119
27 Tyler St Boston, 02111
1 State St Ste 1500 Boston, 02108

Please when verifying a new bug in regards to content not been there, use production instead of UAT. 
@andrebtlima I will close this bug for now. It is not a bug.

Fix -> won't fix. Not a bug. 
You can retest in production.

**Closed as completed by subaha-cob** 2020-12-19 16:29 UTC
