### ISSUE TITLE
404 Error While Using the Website.dox

### ISSUE THREAD

**Issue by jill-iterators** [CityOfBoston/Iterators#157] opened 2020-08-26 21:51 UTC
While testing for Accessibility, I found a 404 Error. 

Here is the link: https://d8-stg.boston.gov/sites/default/files/file/2020/01/plastic-bag-waiver.pdf.docx
<img width="1534" alt="Screen Shot 2020-08-26 at 5 45 02 PM" src="https://user-images.githubusercontent.com/53226162/91360632-d0bee880-e7c4-11ea-9a96-55267468d968.png">

**Comment by subaha-cob** [comment] 2020-08-31 12:54
@jill-iterators where did you find this bug? @andrebtlima this is a broken URL. We will need the page you found this on so we can find it and fix it. Thanks!

**Comment by jill-iterators** [comment] 2020-08-31 18:41
Hi Stella, 
I put the link at the top of the page, right after... While testing for Accessibility, I found a 404 Error. The image appeared after I pasted the link and I can see it's hard to see. The link is attached below.

![image](https://user-images.githubusercontent.com/53226162/91754681-d2f3bf00-eb97-11ea-8543-144f2a0a3999.png)

**Comment by subaha-cob** [comment] 2020-09-01 14:33
@jill-iterators I wanted the actual page this link was linked to so i can provide that to the Content editor.

**Comment by jill-iterators** [comment] 2020-09-01 17:14
Here is the link:

https://d8-stg.boston.gov/departments/environment/understanding-plastic-bag-ordinance

**Comment by subaha-cob** [comment] 2020-09-01 18:31
Thank you @jill-iterators .

**Comment by subaha-cob** [comment] 2020-09-02 13:30
@jill-iterators I cannot reproduce the error. Can you test again or better still do a video capture if you are still producing the error.

**Comment by jill-iterators** [comment] 2020-09-02 15:31
@subaha-cob While trying to find the link again, I cannot find and wonder if it's fixed. I did find another 404 error in the same area. Attaching bug report and video here. 
[2020 09 02, Plastic Bag Ordinance 404 Error.mp4.zip](https://github.com/CityOfBoston/Iterators/files/5163263/2020.09.02.Plastic.Bag.Ordinance.404.Error.mp4.zip)
2020 09 02, Plastic Bag Ordinance 404 Error.docx

**Comment by jill-iterators** [comment] 2020-09-02 15:32
[2020 09 02, Plastic Bag Ordinance 404 Error.docx](https://github.com/CityOfBoston/Iterators/files/5163268/2020.09.02.Plastic.Bag.Ordinance.404.Error.docx)

**Comment by subaha-cob** [comment] 2020-09-02 15:39
@jill-iterators I think I know what the problem may be now. The files are not really missing but because the database was dumped onto staging and not the files, it looks like they are missing on Staging. For missing files please test on Production/live site first before logging in a bug. 

I am closing to move this ticket to for review because it is working on Production. @andrebtlima please take note when you test.

**Comment by andrebtlima** [comment] 2020-09-09 13:31
Looks like this is working on production so closing.

**Closed as completed by andrebtlima** 2020-09-09 13:31 UTC
Labels: content, Functional
