### ISSUE TITLE
Secondary Header does not appear on staging site

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#23] opened 2019-08-15 14:19 UTC
Screengrab/videos (insert file names here)
2019 08 15, Secondary Header does not appear on staging site.mp4
[2019 08 15, Secondary Header does not appear on staging site.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3505870/2019.08.15.Secondary.Header.does.not.appear.on.staging.site.mp4.zip)

Link
Drupal 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/45351

Drupal 7 Link:
•	https://boston.gov/node/45351

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Drupal 8 node 45351 page  > Header > Second Header

Brief Description
The second header (Containing link to Mayor on Mayor events, 2018 winners, and Helpful Resources section of the page) does not appear on the Drupal 8 version of the page

Steps to reproduce
1. Open the Drupal 7 and Drupal 8 links for node 45351 as an anonymous user
2. Scroll down the Drupal 7 page until a secondary header shows up
3. Scroll down the same amount on the Drupal 8 page

Desired Result
•	A secondary header shows up on both pages

Actual Result
•	A secondary header does not show up on both pages

**Comment by davidrkupton** [comment] 2019-08-22 12:12
@mmcgowanBOS 
I cannot reproduce on firefox or chrome.
I don't have access to safari or IE.
This would be a js (possibly css) issue it so it could easily be an issue just on those browser types.

**Comment by mmcgowanBOS** [comment] 2019-08-22 13:13
@davidrkupton , I can confirm that the breadcrumb menu is not appearing on Safari when scrolling further down the page. I inspected the page and there is an error loading a specific JS file named 'inpage-menu.boston.js'. This I'm pretty sure is the issue. There were no other errors in the console. I've attached a screengrab of the error console as well.
<img width="944" alt="Screen Shot 2019-08-22 at 9 09 14 AM" src="https://user-images.githubusercontent.com/44584567/63517491-157eb800-c4bd-11e9-915d-da29641dbc03.png">

**Comment by davidrkupton** [comment] 2019-08-22 14:13
OK I have renamed this file, removing the "-" and using a "_".
IDK if this will fix, we can test.
Bit of a long shot, but can't see what else would cause safari not to find the file when other (non-apple) browsers are OK.

**Comment by ollie-iterators** [comment] 2019-08-23 14:58
The secondary menu is still not visible on Safari for the Events page.
[2019 08 23, Secondary Header does not appear on staging site.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3535050/2019.08.23.Secondary.Header.does.not.appear.on.staging.site.mp4.zip)

**Comment by mmcgowanBOS** [comment] 2019-08-26 19:12
I tested again in Safari, and can confirm that the menu is still not showing, BUT the broken link to the "..menu" js file is now fixed. See screen shot attached.
<img width="1406" alt="Screen Shot 2019-08-26 at 3 10 44 PM" src="https://user-images.githubusercontent.com/44584567/63716372-dc737a00-c813-11e9-8a00-adf50c5c4c34.png">

**Comment by davidrkupton** [comment] 2019-08-26 20:28
Done.  Works on browser stack.

**Closed as completed** 2019-09-05 18:05 UTC
Labels: content, User / Anonymous
