### ISSUE TITLE
The Visiting Boston Section Buttons causes the page to go downward on the Drupal 8 site past the section and then move upwards to correct the downward movement

### ISSUE THREAD

**Issue by ollie-iterators** [CityOfBoston/Iterators#80] opened 2019-08-30 14:59 UTC
Screengrab/videos (insert file names here)
2019 08 30, Dupral 8 Visiting Boston page section buttons cause the page to go downward past the section and then go back up.mp4
[2019 08 30, Dupral 8 Visiting Boston page section buttons cause the page to go downward past the section and then go back up.mp4.zip](https://github.com/CityOfBoston/Iterators/files/3560424/2019.08.30.Dupral.8.Visiting.Boston.page.section.buttons.cause.the.page.to.go.downward.past.the.section.and.then.go.back.up.mp4.zip)

Link and Node #
Dupral 8 Link:
•	http://bostond8stg.prod.acquia-sites.com/node/6661 

Dupral 7 Link:
•	http://boston.gov/node/6661 

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.14.6 > Safari 12.1.2

Section
(Page > Area > Element)
Visiting Boston page > Section Buttons > how the page moves downward

Brief Description
The Visiting Boston Section Buttons causes the page to go downward on the Drupal 8 site past the section and then move upwards to correct the downward movement

Steps to reproduce
1. Open the Drupal 7 and 8 sites for node 6661
2.  Click on a section for both of the pages and see how they react

Desired Result
•	The pages go to the sections in a normal manner

Actual Result
•	On the Drupal 8 site, the page goes downward to the section, then moves back upwards to correct going past the section it was going to

**Comment by jimafisk** [comment] 2019-09-03 15:54
This appears to be a safari only bug (tested with Firefox 68.0.2 and Chrome 76.0.3809.100). This should be fixed, but since it's present in D7 and D8 I propose moving to a later phase. @mmcgowanBOS @davidrkupton thoughts?

**Comment by davidrkupton** [comment] 2019-09-03 20:57
This is expected behaviour since the menu collapses after the scroll page starts.
The little shift upwards is because of the menubar collapsing out of the page and taking up less space.

**Closed as completed** 2019-09-05 17:44 UTC
Labels: bug, User / Anonymous
