### ISSUE TITLE
The Image link for the Logo of “My Brother’s Keeper Boston” is broken

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#224] opened 2021-12-17 18:20 UTC
Brief Description
The Image link for the Logo of “My Brother’s Keeper Boston” is broken

Screengrab/videos (insert file names here)
https://www.loom.com/share/0cb92e0ea9974d30b9170afb4f6a01c9

Tester (first name)
Andrew

Link
Production URL: https://www.boston.gov/civic-engagement/my-brothers-keeper-boston
UAT URL: https://d8-uat.boston.gov/civic-engagement/my-brothers-keeper-boston 
Environment
(Device > OS > Browser)
Computer > Windows 10 > Google Chrome 96

Type of Bug:  Functional, Accessibility or Content
Functional

Steps to reproduce
1)	00:00, Launch pages in Private Browsers
a)	00:05, The UAT page is displayed on the left and the Production page is displayed on the right
2)	00:10, BUG: the image link for “My Brother’s Keeper Boston”’s Logo is broken, leaving the universal “Image Missing” icon in its place

Desired Result
•	All images display propperly

Actual Result
•	The Image link for the Logo of “My Brother’s Keeper Boston” is broken

**Comment by subaha-cob** [comment] 2021-12-20 14:22
@david-iterators Won't fix. Missing image issue should resolve on Staging. Content changes can be retested on Staging when we get there.

RETEST ON STAGE!!!! Pending Stage Deploy.
https://d8-stg.boston.gov/

**Comment by Andrew-Iterators** [comment] 2021-12-29 16:21
this bug is still present on the staging site

**Comment by subaha-cob** [comment] 2021-12-29 16:27
> this bug is still present on the staging site

Yes it will be because we haven't pushed anything to staging yet. Pending Stage Deploy :) 

Once we go to stage I will flag again for testing.

**Comment by david-iterators** [comment] 2022-01-11 19:51
Hi @subaha-cob , The broken link is still present on staging as of today.  We would like to double check if staging is ready for us, or if we should wait.  We used https://d8-stg.boston.gov/civic-engagement/my-brothers-keeper-boston in an Incognito window.  Thanks

**Comment by Andrew-Iterators** [comment] 2022-01-11 21:00
This bug is not resolved on the staging site. I also wrote up a new report if that is helpful

**Comment by subaha-cob** [comment] 2022-01-11 22:12
@david-iterators @Andrew-Iterators I have update this page to point to images on production. As I mentioned earlier the issue is that the images are in production and have not been downloaded to the other environments yet due to space constraint. For now, so that we can move forward we have turned on the module to sync the images.

This is all set now. Please retest!

**Comment by Andrew-Iterators** [comment] 2022-01-12 18:58
this bug is now resolved

**Closed as completed** 2022-01-13 01:45 UTC
