### ISSUE TITLE
Parsing Errors

### ISSUE THREAD

**Issue by david-iterators** [CityOfBoston/Iterators#199] opened 2020-11-10 02:34 UTC
Screengrab/videos (insert file names here)
2020 11 07, HTML Parsing Report.pdf

Link
https://www.boston.gov/my-neighborhood

Node # (if known)

Type of User:  Anonymous

Environment
(Device > OS > Browser)
Computer > MacOS 10.15.7 > Safari

Trusted Tester Test
Parsing, WCAG 4.1.1
https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html 

Brief Description
Parsing Errors

Steps to reproduce
1)	Send the link through a parsing checker, such as https://validator.w3.org
2)	Obtain the attached report

Desired Result
•	No HTML parsing errors

Actual Result
•	Several HTML parsing errors and warnings
[2020 11 07, HTML Parsing Report.pdf](https://github.com/CityOfBoston/Iterators/files/5514462/2020.11.07.HTML.Parsing.Report.pdf)

**Comment by subaha-cob** [comment] 2020-11-25 18:51
@reillyzlab this is not just MNL. It involves the entire website. The errors are on the navigation the structure of the site and the components. Will involve testing the entire site, so stay tuned. I will write out the details when I am done.

**Comment by david-iterators** [comment] 2021-04-05 18:45
Hi @subaha-cob and @mmcgowanBOS Here is a reference with a little more background about high priority parsing errors.  Thanks
[Parsing Errors, Deprecating SC 4.1.1 · Issue #770 · w3c, wcag.pdf](https://github.com/CityOfBoston/Iterators/files/6259976/Parsing.Errors.Deprecating.SC.4.1.1.Issue.770.w3c.wcag.pdf)

**Comment by subaha-cob** [comment] 2021-04-07 18:21
Duplicate of HTML Validation warnings, boston.gov #207

**Comment by subaha-cob** [comment] 2021-04-22 21:04
Duplicate of #207

**Closed as completed** 2021-04-22 21:04 UTC
Labels: Accessibility, MyNeighborhood
